# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wzrost', models.CharField(max_length=200)),
                ('Imie', models.TextField()),
                ('Nazwisko', models.TextField()),
                ('BirthDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
